Repository DuckDuckStudio/winget-tools, pull requests merged in 2025-04, with the labels that each got.

#191 [Auto] 自动化日志 20250401/JosephBurnett.jd-2.2.2.log
  logs/20250401/JosephBurnett.jd-2.2.2.log
Labels: auto

#192 [Auto] 自动化日志 20250402/ALE.Rainbow.log
  logs/20250402/ALE.Rainbow.log
Labels: auto

#193 [Auto] 自动忽略追加 - httpspbankbankcommcnpersonbankdownloadSecEditCFCAforBoComexe
  auto_script/check/checker/Program.cs
Labels: auto

#194 [Auto] 自动忽略追加 - jisupdfeditorcom
  auto_script/check/checker/Program.cs
Labels: auto

#195 [Auto] 自动忽略移除 - httpsdljisupdfeditorcomjisupdfeditor_setup_3062exe
  auto_script/check/checker/Program.cs
Labels: auto

#197 [Auto] 自动忽略追加 - httpscatsxposs-cn-hongkongaliyuncscom
  auto_script/check/checker/Program.cs
Labels: auto

#200 [Auto] 自动忽略追加 - httpsopenrainbowcomdownloadsRainbow_Installer_User_Electron_v213920exe
  auto_script/check/checker/Program.cs
Labels: auto

#202 [Auto] 自动化日志 20250403/BeyondATC.TrafficMap-1.1.1.log
  logs/20250403/BeyondATC.TrafficMap-1.1.1.log
Labels: auto

#201 [Auto] 自动化日志 20250403/DuckStudio.Sundry-1.1.11.log
  logs/20250403/DuckStudio.Sundry-1.1.11.log
Labels: auto

#203 [Auto] 自动忽略追加 - httpsota-downloadsnvidiacomotaGeForceNOW
  auto_script/check/checker/Program.cs
Labels: auto

#204 [Auto] 自动化日志 20250404/ppy.osu.stable-20250401.2.log
  logs/20250404/ppy.osu.stable-20250401.2.log
Labels: auto

#205 [Auto] 自动忽略追加 - httpsopenrainbowcomdownloads
  auto_script/check/checker/Program.cs
Labels: auto

#206 [Auto] 自动忽略移除 - httpsota-downloadsnvidiacomotaGeForceNOW
  auto_script/check/checker/Program.cs
Labels: auto

#207 [Auto] 自动忽略移除 - httpsopenrainbowcomdownloadsRainbow_Installer_User_Electron_v213920exe
  auto_script/check/checker/Program.cs
Labels: auto

#208 [Auto] 自动忽略移除 - httpsopenrainbowcomdownloads
  auto_script/check/checker/Program.cs
Labels: auto

#210 [Auto] 自动化日志 20250410/ppy.osu.stable-20250401.2.log
  logs/20250410/ppy.osu.stable-20250401.2.log
Labels: auto

#211 log add - DuckStudio.GitHubView
  logs/20250410/DuckStudio.GitHubView.Nightly-2025.04.10.14373190636.log
Labels: DEV-开发分支合并, auto

#212 [Auto] 自动化日志 20250416/DuckStudio.FufuTools-1.3.8.log
  logs/20250416/DuckStudio.FufuTools-1.3.8.log
Labels: auto

#213 [Auto] 自动化日志 20250416/DuckStudio.FufuTools-1.3.7.1.log
  logs/20250416/DuckStudio.FufuTools-1.3.7.1.log
Labels: auto

#214 [Auto] 自动化日志 20250416/MinistryOfEducationOfThePRC.SmartSchools-1.3.7.log
  logs/20250416/MinistryOfEducationOfThePRC.SmartSchools-1.3.7.log
Labels: auto

#215 [Auto] 自动化日志 20250416/MinistryOfEducationOfThePRC.SmartSchools-1.3.8.log
  logs/20250416/MinistryOfEducationOfThePRC.SmartSchools-1.3.8.log
Labels: auto

#216 [Auto] 自动化日志 20250416/XBMCFoundation.Kodi.log
  logs/20250416/XBMCFoundation.Kodi.log
Labels: auto

#217 [Auto] 自动化日志 20250417/ClassicOldSong.Apollo.log
  logs/20250417/ClassicOldSong.Apollo.log
Labels: auto

#218 [Auto] 自动化日志 20250417/ClassicOldSong.Apollo.log
  logs/20250417/ClassicOldSong.Apollo.log
Labels: auto

#219 [Auto] 自动化日志 20250417/monkeyWie.Gopeed.log
  logs/20250417/monkeyWie.Gopeed.log
Labels: auto

#220 添加 WIP 忽略
  auto_script/check/checker/Program.cs
Labels: DEV-开发分支合并, auto

#222 [Auto] 自动忽略移除 - httpsgithubcomClassicOldSongApolloreleasesdownloadv034Apolloexe
  auto_script/check/checker/Program.cs
Labels: auto

#223 [Auto] 自动化日志 20250418/DuckStudio.Sundry-1.1.12.log
  logs/20250418/DuckStudio.Sundry-1.1.12.log
Labels: auto

#224 [Auto] 自动化日志 20250418/ClassicOldSong.Apollo.log
  logs/20250418/ClassicOldSong.Apollo.log
Labels: auto

#225 chore: 同步 main 分支修改
  .github/workflows/check-url-cai.yml
  .github/workflows/df.yml
  .gitignore
  auto_script/check/checker/Program.cs
  logs/20250401/JosephBurnett.jd-2.2.2.log
  logs/20250402/ALE.Rainbow.log
  logs/20250403/BeyondATC.TrafficMap-1.1.1.log
  logs/20250403/DuckStudio.Sundry-1.1.11.log
  logs/20250403/Hugo.Hugo.Deploy-0.145.0.log
  logs/20250404/ppy.osu.stable-20250401.2.log
  logs/20250410/DuckStudio.GitHubView.Nightly-2025.04.10.14373190636.log
  logs/20250410/ppy.osu-2025.321.0.log
  logs/20250410/ppy.osu.stable-20250401.2.log
  logs/20250416/DuckStudio.FufuTools-1.3.7.1.log
  logs/20250416/DuckStudio.FufuTools-1.3.8.log
  logs/20250416/MinistryOfEducationOfThePRC.SmartSchools-1.3.7.log
  logs/20250416/MinistryOfEducationOfThePRC.SmartSchools-1.3.8.log
  logs/20250416/XBMCFoundation.Kodi.log
  logs/20250417/ClassicOldSong.Apollo.log
  logs/20250417/monkeyWie.Gopeed.log
  logs/20250418/ClassicOldSong.Apollo.log
  logs/20250418/DuckStudio.Sundry-1.1.12.log
Labels: DEV-开发分支合并

#226 [Auto] 自动忽略追加 - httpsstaticcentbrowsercn
  auto_script/check/checker/Program.cs
Labels: auto

#227 [Auto] 自动化日志 20250419/Heaventools.ResourceTunerConsole-2.24.log
  logs/20250419/Heaventools.ResourceTunerConsole-2.24.log
Labels: auto

#228 [Auto] 自动忽略追加 - httpsdlhe3appcom
  auto_script/check/checker/Program.cs
Labels: auto

#229 [Auto] 自动化日志 20250420/ppy.osu-2025.418.0.log
  logs/20250420/ppy.osu-2025.418.0.log
Labels: auto

#230 [Auto] 自动忽略追加 - httpsgithubcomalagredeznote-appreleasesdownloadv272znote-Setup-272exe
  auto_script/check/checker/Program.cs
Labels: auto

#231 [Auto] 自动忽略追加 - httpsdlbandicamcomoldBDCAMSETUP_ENG_3_2_1_1107EXE
  auto_script/check/checker/Program.cs
Labels: auto

#232 [Auto] 自动化日志 20250420/Yuanli.uTools-5.1.0.log
  logs/20250420/Yuanli.uTools-5.1.0.log
Labels: auto

#233 [Auto] 自动化日志 20250420/XBMCFoundation.Kodi-19.1.0.0.log
  logs/20250420/XBMCFoundation.Kodi-19.1.0.0.log
Labels: auto

#234 [Auto] 自动忽略追加 - httpscdn1waterfoxnetwaterfoxreleases
  auto_script/check/checker/Program.cs
Labels: auto

#235 [Auto] 自动忽略追加 - httpsdownloadwondersharecomcbs_down
  auto_script/check/checker/Program.cs
Labels: auto

#236 [Auto] 自动忽略追加 - httpsdownloadstableaucompublic
  auto_script/check/checker/Program.cs
Labels: auto

#237 [Auto] 自动忽略追加 - httpsspthsicnstaticS3mobileweb-upload-static-serverfileapp_6downloadcenterTHS_insoft
  auto_script/check/checker/Program.cs
Labels: auto

#238 [Auto] 自动化日志 20250421/ppy.osu-2025.418.1.log
  logs/20250421/ppy.osu-2025.418.1.log
Labels: auto

#239 [Auto] 自动化日志 20250421/ppy.osu-2025.420.0.log
  logs/20250421/ppy.osu-2025.420.0.log
Labels: auto

#240 [Auto] 自动忽略移除 - httpsdlhe3appcomhttpsgithubcomalagredeznote-appreleasesdownloadv272znote-Setup-272exehttpsdlbandicamcomoldBDCAMSETUP_ENG_3_2_1_1107EXE
  auto_script/check/checker/Program.cs
Labels: auto

#241 [Auto] 自动忽略追加 - httpswwwgtopalacomdownload
  auto_script/check/checker/Program.cs
Labels: auto

#242 [Auto] 自动忽略移除 - httpswwwgtopalacomdownload
  auto_script/check/checker/Program.cs
Labels: auto

#243 [Auto] 自动忽略移除 - httpscatsxposs-cn-hongkongaliyuncscom
  auto_script/check/checker/Program.cs
Labels: auto

#244 [Auto] 自动化日志 20250422/Abacus.AbaClient-2.3.730.log
  logs/20250422/Abacus.AbaClient-2.3.730.log
Labels: auto

#246 [Auto] 自动化日志 20250422/IDEA.ReadPaper-1.29.0.log
  logs/20250422/IDEA.ReadPaper-1.29.0.log
Labels: auto

#247 [Auto] 自动化日志 20250423/ManicTime.ManicTime-24.1.0.7.log
  logs/20250423/ManicTime.ManicTime-24.1.0.7.log
Labels: auto

#249 [Auto] 自动化日志 20250423/ManicTime.ManicTime-25.1.1.0.log
  logs/20250423/ManicTime.ManicTime-25.1.1.0.log
Labels: auto

#251 [Auto] 自动化日志 20250423/ManicTime.ManicTime-25.1.3.0.log
  logs/20250423/ManicTime.ManicTime-25.1.3.0.log
Labels: auto

#252 [Auto] 自动化日志 20250423/ManicTime.ManicTime-25.1.5.0.log
  logs/20250423/ManicTime.ManicTime-25.1.5.0.log
Labels: auto

#250 [Auto] 自动化日志 20250423/ManicTime.ManicTime-25.1.2.0.log
  logs/20250423/ManicTime.ManicTime-25.1.2.0.log
Labels: auto

#253 [Auto] 自动化日志 20250423/Bloret.BloretLauncher-5.log
  logs/20250423/Bloret.BloretLauncher-5.log
Labels: auto

#254 [Auto] 自动化日志 20250423/Bloret.BloretLauncher-6.log
  logs/20250423/Bloret.BloretLauncher-6.log
Labels: auto

#255 [Auto] 自动忽略追加 - httpsgithubcomwinsidersssi-buildsreleasesdownload3225044321systeminformer-3225044321-canary-setupexe
  checker/Program.cs
Labels: auto

#256 [Auto] 自动忽略追加 - httpscatsxposs-cn-hongkongaliyuncscom
  checker/Program.cs
Labels: auto

#257 [Auto] 自动化日志 20250424/Codemao.TurtleEditor.2-2.7.4.log
  logs/20250424/Codemao.TurtleEditor.2-2.7.4.log
Labels: auto

#258 [Auto] 自动化日志 20250424/Codemao.TurtleEditor.2-2.7.5.log
  logs/20250424/Codemao.TurtleEditor.2-2.7.5.log
Labels: auto

#259 [Auto] 自动化日志 20250424/Codemao.TurtleEditor.1-1.8.4.log
  logs/20250424/Codemao.TurtleEditor.1-1.8.4.log
Labels: auto

#260 [Auto] 自动化日志 20250424/Codemao.TurtleEditor.1-1.8.5.log
  logs/20250424/Codemao.TurtleEditor.1-1.8.5.log
Labels: auto

#261 [Auto] 自动化日志 20250424/Codemao.TurtleEditor.1-1.8.6.log
  logs/20250424/Codemao.TurtleEditor.1-1.8.6.log
Labels: auto

#262 [Auto] 自动忽略追加 - httpsfiles02tchsptcomdown
  checker/Program.cs
Labels: auto

#264 [Auto] 自动化日志 20250425/HuoHuaSiWei.HuoHuaBianCheng-3.18.1.log
  logs/20250425/HuoHuaSiWei.HuoHuaBianCheng-3.18.1.log
Labels: auto

#263 [Auto] 自动化日志 20250425/HuoHuaSiWei.HuoHuaSiWei-25.4.18.2187402.log
  logs/20250425/HuoHuaSiWei.HuoHuaSiWei-25.4.18.2187402.log
Labels: auto

#265 [Auto] 自动化日志 20250425/ESET.AVRemover-1.6.7.0.log
  logs/20250425/ESET.AVRemover-1.6.7.0.log
Labels: auto

#266 [Auto] 自动忽略追加 - httpsdownloadesetcomcomesettoolsinstallersav_removerlatestavremover_arm64_enuexe
  checker/Program.cs
Labels: auto

#267 [Auto] 自动忽略移除 - httpsgithubcomwinsidersssi-buildsreleasesdownload3225044321systeminformer-3225044321-canary-setupexe
  checker/Program.cs
Labels: auto

#269 自动化日志 20250425/Alibaba.aDrive-Remove.log
  logs/20250425/Alibaba.aDrive-Remove.log
Labels: auto

#268 [Auto] 自动化日志 20250425/Alibaba.Quark-2.5.5.304.log
  logs/20250425/Alibaba.Quark-2.5.5.304.log
Labels: auto

#271 自动化日志 20250425/Alibaba.DingTalk-Remove.log
  logs/20250425/Alibaba.DingTalk-Remove.log
Labels: auto

#273 [Auto] 自动化日志 20250426/Ritlabs.TheBat-11.4.1.log
  logs/20250426/Ritlabs.TheBat-11.4.1.log
Labels: auto

#274 [Auto] 自动忽略追加 - httpsaurorabuildercomdownloadsAurora20Setupzip
  checker/Program.cs
Labels: auto

#275 自动化日志 20250426/BandicamCompany.Bandicam-Remove.log
  logs/20250426/BandicamCompany.Bandicam-Remove.log
Labels: auto

#277 [Auto] 自动化日志 20250427/Brosix.Brosix-5.1.7.log
  logs/20250427/Brosix.Brosix-5.1.7.log
Labels: auto

#279 [Auto] 自动化日志 20250427/GiulioSorrentino.wheelofnumfortune.avalonia-0.4.0.log
  logs/20250427/GiulioSorrentino.wheelofnumfortune.avalonia-0.4.0.log
Labels: auto

#278 [Auto] 自动忽略追加 - httpscdn-dlyinxiangcom
  checker/Program.cs
Labels: auto

#280 [Auto] 自动化日志 20250428/MinistryOfEducationOfThePRC.SmartSchools-1.3.9.log
  logs/20250428/MinistryOfEducationOfThePRC.SmartSchools-1.3.9.log
Labels: auto

#281 [Auto] 自动化日志 20250428/MinistryOfEducationOfThePRC.SmartSchools-1.3.3.log
  logs/20250428/MinistryOfEducationOfThePRC.SmartSchools-1.3.3.log
Labels: auto

#282 [Auto] 自动化日志 20250428/xemu-project.xemu-0.7.96.log
  logs/20250428/xemu-project.xemu-0.7.96.log
Labels: auto

#283 [Auto] 自动忽略追加 - httpsgithubcomlutzroedernetronreleasesdownload
  checker/Program.cs
Labels: auto

#284 [Auto] 自动忽略追加 - httpsxmcl-release-msazureedgenetreleases
  checker/Program.cs
Labels: auto

#285 [Auto] 自动忽略追加 - httpsgithubcomkiwixkiwix-js-windowsreleasesdownloadv262-WikivoyageWikivoyage-by-Kiwix-Setup-262-Eexe
  checker/Program.cs
Labels: auto

#287 [Auto] 自动忽略追加 - httpsdownloadmono-projectcomarchive
  checker/Program.cs
Labels: auto

#288 [Auto] 自动忽略追加 - httpwwwheaventoolscomfiles11hFgnI0sFlexHex_editor_setupexe
  checker/Program.cs
Labels: auto

#289 [Auto] 自动忽略移除 - httpsgithubcomlutzroedernetronreleasesdownload
  checker/Program.cs
Labels: auto

#290 [Auto] 自动忽略移除 - httpsxmcl-release-msazureedgenetreleaseshttpsgithubcomkiwixkiwix-js-windowsreleasesdownloadv262-WikivoyageWikivoyage-by-Kiwix-Setup-262-Eexe
  checker/Program.cs
Labels: auto

#291 [Auto] 自动化日志 20250430/Z-DBackup.Z-Cron-6.4.log
  logs/20250430/Z-DBackup.Z-Cron-6.4.log
Labels: auto

#292 [Auto] 自动忽略追加 - httpswwwz-downloaddedownzcronzip
  checker/Program.cs
Labels: auto

#293 自动化日志 20250430/RingCentral.RingCentral-Remove.log
  logs/20250430/RingCentral.RingCentral-Remove.log
Labels: auto

#294 [Auto] 自动忽略追加 - httpscdnkdeorg
  checker/Program.cs
Labels: auto
