Repository DuckDuckStudio/winget-tools, pull requests merged in 2025-06, with the labels that each got.

#375 [Auto] 自动化日志 logs/2025/06/01/AlexanderPro.SmartSystemMenu-2.31.0.log
  logs/2025/06/01/AlexanderPro.SmartSystemMenu-2.31.0.log
Labels: auto

#377 [Auto] 自动化日志 logs/2025/06/02/glueckkanja.KONNEKT-2.9.1.log
  logs/2025/06/02/glueckkanja.KONNEKT-2.9.1.log
Labels: auto

#378 docs: CODEOWNERS
  .github/CODEOWNERS
Labels: DEV-开发分支合并, DEV-测试通过

#379 [Auto] 自动忽略追加 - httpinstallerjdownloaderorgJD2SilentSetup_x86exe
  checker/Program.cs
Labels: auto

#381 [Auto] 自动化日志 logs/2025/06/03/AmericanRadioRelayLeague.TrustedQSL-2.6.5.log
  logs/2025/06/03/AmericanRadioRelayLeague.TrustedQSL-2.6.5.log
Labels: auto

#380 [Auto] 自动化日志 logs/2025/06/03/AmericanRadioRelayLeague.TrustedQSL-2.7.2.log
  logs/2025/06/03/AmericanRadioRelayLeague.TrustedQSL-2.7.2.log
Labels: auto

#384 [Auto] 自动化日志 logs/2025/06/06/DuckStudio.FufuTools-1.3.9.log
  logs/2025/06/06/DuckStudio.FufuTools-1.3.9.log
Labels: auto

#386 [Auto] 自动化日志 logs/2025/06/07/CapricornConsultingGmbH.Vigoon-2.4.2261.log
  logs/2025/06/07/CapricornConsultingGmbH.Vigoon-2.4.2261.log
Labels: auto

#391 [Auto] 自动化日志 logs/2025/06/08/QmmpDevelopmentTeam.qmmp-1.6.0.log
  logs/2025/06/08/QmmpDevelopmentTeam.qmmp-1.6.0.log
Labels: auto

#390 [Auto] 自动化日志 logs/2025/06/08/QmmpDevelopmentTeam.qmmp-2.1.5.log
  logs/2025/06/08/QmmpDevelopmentTeam.qmmp-2.1.5.log
Labels: auto

#389 [Auto] 自动化日志 logs/2025/06/08/QmmpDevelopmentTeam.qmmp-1.4.3.log
  logs/2025/06/08/QmmpDevelopmentTeam.qmmp-1.4.3.log
Labels: auto

#393 [Auto] 自动化日志 logs/2025/06/08/CapricornConsultingGmbH.Vigoon-1.0.0.log
  logs/2025/06/08/CapricornConsultingGmbH.Vigoon-1.0.0.log
Labels: auto

#396 [Auto] 自动化日志 logs/2025/06/09/DuckStudio.Sundry-1.2.2.log
  logs/2025/06/09/DuckStudio.Sundry-1.2.2.log
Labels: auto

#395 [Auto] 自动化日志 logs/2025/06/09/LGElectronics.SmartShare-33.2.3.1511.1201.log
  logs/2025/06/09/LGElectronics.SmartShare-33.2.3.1511.1201.log
Labels: auto

#397 [Auto] 自动化日志 logs/2025/06/09/Codemao.kitten.4-4.11.15.log
  logs/2025/06/09/Codemao.kitten.4-4.11.15.log
Labels: auto

#400 [Auto] 自动化日志 logs/2025/06/10/DuckStudio.ChineseGit-3.3.log
  logs/2025/06/10/DuckStudio.ChineseGit-3.3.log
Labels: auto

#401 [Auto] 自动化日志 logs/2025/06/10/DuckStudio.Sundry-1.2.3.log
  logs/2025/06/10/DuckStudio.Sundry-1.2.3.log
Labels: auto

#403 [Auto] 自动化日志 logs/2025/06/11/XBMCFoundation.Kodi-18.6.0.0.log
  logs/2025/06/11/XBMCFoundation.Kodi-18.6.0.0.log
Labels: auto

#406 [Auto] 自动化日志 logs/2025/06/12/DaiyuuNobori.Win10Pcap-10.2.5002.log
  logs/2025/06/12/DaiyuuNobori.Win10Pcap-10.2.5002.log
Labels: auto

#408 [Auto] 自动忽略移除 - httpinstallerjdownloaderorgJD2SilentSetup_x64exehttpinstallerjdownloaderorgJD2SilentSetup_x86exe
  checker/Program.cs
Labels: auto

#410 [Auto] 自动化日志 logs/2025/06/15/PixPin.PixPin.Beta-2.1.0.0.log
  logs/2025/06/15/PixPin.PixPin.Beta-2.1.0.0.log
Labels: auto

#409 feat: 自定义最大并发数
  .github/workflows/check-url-cai.yml
  checker/Program.cs
Labels: DEV-开发分支合并, DEV-测试通过, 新功能

#411 [Auto] 自动化日志 logs/2025/06/17/PixPin.PixPin.Beta-2.1.0.0.log
  logs/2025/06/17/PixPin.PixPin.Beta-2.1.0.0.log
Labels: auto

#412 [Auto] 自动化日志 logs/2025/06/20/HolographicHat.YaeAchievement-5.6.0.log
  logs/2025/06/20/HolographicHat.YaeAchievement-5.6.0.log
Labels: auto

#413 [Auto] 自动化日志 logs/2025/06/21/Fossil.Fossil-2.26.log
  logs/2025/06/21/Fossil.Fossil-2.26.log
Labels: auto

#414 [Auto] 自动化日志 logs/2025/06/21/DuckStudio.Sundry-1.2.4.log
  logs/2025/06/21/DuckStudio.Sundry-1.2.4.log
Labels: auto

#417 [Auto] 自动化日志 logs/2025/06/22/DuckStudio.Sundry-1.2.6.log
  logs/2025/06/22/DuckStudio.Sundry-1.2.6.log
Labels: auto

#420 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.0.1.log
  logs/2025/06/24/DuckStudio.Sundry-1.0.1.log
Labels: auto

#435 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.1.12.log
  logs/2025/06/24/DuckStudio.Sundry-1.1.12.log
Labels: auto

#437 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.1.14.log
  logs/2025/06/24/DuckStudio.Sundry-1.1.14.log
Labels: auto

#449 ci(重试拉取请求): 启用定时运行
  .github/workflows/retry-PR.yaml
Labels: DEV-开发分支合并, auto

#447 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.2.2.log
  logs/2025/06/24/DuckStudio.Sundry-1.2.2.log
Labels: auto

#445 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.2.0.log
  logs/2025/06/24/DuckStudio.Sundry-1.2.0.log
Labels: auto

#444 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.1.9.log
  logs/2025/06/24/DuckStudio.Sundry-1.1.9.log
Labels: auto

#439 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.1.3.log
  logs/2025/06/24/DuckStudio.Sundry-1.1.3.log
Labels: auto

#443 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.1.8.log
  logs/2025/06/24/DuckStudio.Sundry-1.1.8.log
Labels: auto

#421 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.0.2.log
  logs/2025/06/24/DuckStudio.Sundry-1.0.2.log
Labels: auto

#441 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.1.6.log
  logs/2025/06/24/DuckStudio.Sundry-1.1.6.log
Labels: auto

#429 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.0.8.log
  logs/2025/06/24/DuckStudio.Sundry-1.0.8.log
Labels: auto

#432 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.1.1.log
  logs/2025/06/24/DuckStudio.Sundry-1.1.1.log
Labels: auto

#424 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.0.3.log
  logs/2025/06/24/DuckStudio.Sundry-1.0.3.log
Labels: auto

#434 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.1.11.log
  logs/2025/06/24/DuckStudio.Sundry-1.1.11.log
Labels: auto

#427 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.0.6.log
  logs/2025/06/24/DuckStudio.Sundry-1.0.6.log
Labels: auto

#418 [Auto] 自动化日志 logs/2025/06/23/DuckStudio.Sundry-1.2.7.log
  logs/2025/06/23/DuckStudio.Sundry-1.2.7.log
Labels: auto

#436 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.1.13.log
  logs/2025/06/24/DuckStudio.Sundry-1.1.13.log
Labels: auto

#425 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.0.4.log
  logs/2025/06/24/DuckStudio.Sundry-1.0.4.log
Labels: auto

#422 [Auto] 自动化日志 logs/2025/06/24/DuckStudio.Sundry-1.0.10.log
  logs/2025/06/24/DuckStudio.Sundry-1.0.10.log
Labels: auto

#451 [Auto] 自动化日志 logs/2025/06/25/nilaoda.BBDown-1.6.3.log
  logs/2025/06/25/nilaoda.BBDown-1.6.3.log
Labels: auto

#452 [Auto] 自动化日志 logs/2025/06/25/DuckStudio.Sundry-1.2.8.log
  logs/2025/06/25/DuckStudio.Sundry-1.2.8.log
Labels: auto
